spring:
  rabbitmq:
    username: rabbitmq
    password: St@#2021
    port: 15672
    addresses: 10.2.17.120
    #开启发送失败返回 10.0.50.101
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量
        concurrency: 2
        #指定最大的消费者数量
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true
  redis:
    redisson:
      file: classpath:config/redisson-prod.yaml

  datasource:
    driver-class-name: com.uxsino.uxdb.Driver
    url: jdbc:uxdb://10.2.17.54:5432/sys_test?stringtype=unspecified
    username: uxdb
    password: uxdb
    filters: stat

    druid:
      async-init: true
      initial-size: 15
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #validation-query: SELECT 1 FROM DUAL
      #connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey}
      filter:
        config:
          enabled: true

sofn:
  cleardata:
    enable: false
    enableRemoveSpace:
      enable: true
      rabbitmq:
        enable: true
      fineReport:
        enable: true
        password: admin
        reportUrl: http://10.2.17.31:8080/webroot/decision/view/report?viewlet=
      inforFlow:
        enable: true
        processModelUrl: http://10.2.17.33:8080/ProcessModeler
      elasticsearch:
        ip: 10.2.17.46
        host: 9200

eureka:
  instance:
    hostname: 10.2.17.64
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://10.2.17.64:8880/eureka/
#      defaultZone: http://localhost:8080/register-service/eureka/


xxl:
  job:
    admin:
      addresses: http://10.2.17.74:8653/xxl-job-admin
    executor:
      appname: sys-job-executor
      port: 8651
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken:

proxy:
  user:
    username: quzhijie
    password: e10adc3949ba59abbe56e057f20f883e

jasypt:
  encryptor:
    password: sofn@2021
