spring:
  rabbitmq:
    password: sofn@123
    username: rabbitmq
    port: 15672
    addresses: 192.168.36.15

    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量
        concurrency: 2
        #指定最大的消费者数量
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
      #开启ack
      direct:
        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true
  datasource:
      driver-class-name: dm.jdbc.driver.DmDriver
      url: jdbc:dm://192.168.36.8:5236/SYSTES?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SYSTES
      password: sofn123!@#

  redis:
    redisson:
      file: classpath:config/redisson-dm.yaml

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.36.7:8880/eureka/



proxy:
  user:
    username: share_api
    password: e10adc3949ba59abbe56e057f20f883e

sofn:
  fineReport:
    enable: true
    password: 123456
    reportUrl: http://218.89.222.119:8080/webroot/decision/view/report?viewlet=
    
jasypt:
  encryptor:
    password: sofn@2021