spring:
  datasource:
    driver-class-name: com.uxsino.uxdb.Driver
    url: jdbc:uxdb://192.168.21.62:5432/AGZIRDD_DEV?stringtype=unspecified
    username: uxdb
    password: sofn@123
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.0.52.7:1521:orcl
#    username: AGZIRDD_TEST
#    password: sofn123
    #publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKQtAC12Y5ptIlNtvEgAAaVz+a0y87PDDYcoEZB8Axxagt0SxRKeb/i6SsjjuUSVpPsR73uJ6J5U1ThgNALfo30CAwEAAQ==

    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    #    username: eep
    #    password: eep
    #    url: jdbc:oracle:thin:@192.168.0.219:1521:orcl

    druid:
      async-init: true
      initial-size: 15
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
#      validation-query: SELECT 1 FROM DUAL
      #connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey}
      filter:
        config:
          enabled: true

#  redis:
#    database: 0
#    host: 10.0.50.101
#    port: 6379

  redis:
    cluster:
      nodes: 10.0.50.103:7000,10.0.50.103:7001,10.0.50.103:7002,10.0.50.103:7003,10.0.50.103:7004,10.0.50.103:7005
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 10
    database: 0

sofn:
  excel:
    create-excel-path: /Users/qiugui/files/sofn
#  cleardata:
#    enable: true

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8880/eureka/

