UPDATE DATA_ANALYSIS_AREA
SET TOTOL_RATE =
CASE
		WHEN COLLECT_RESOURCE = 0 THEN
		0 ELSE STRAW_UTILIZATION * 100 / COLLECT_RESOURCE
	END;

UPDATE data_analysis_city
SET TOTOL_RATE =
CASE
		WHEN COLLECT_RESOURCE = 0 THEN
		0 ELSE STRAW_UTILIZATION * 100 / COLLECT_RESOURCE
	END;


UPDATE data_analysis_provice
SET TOTOL_RATE =
CASE
		WHEN COLLECT_RESOURCE = 0 THEN
		0 ELSE STRAW_UTILIZATION *100 / COLLECT_RESOURCE
	END;